### ISSUE TITLE
Create Superset for SNEHA

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/docker-superset#1]
docker latest release - use config.py from current sneha
? should we run superset on unicorn versus nginx ? https://superset.apache.org/docs/installation/configuring-superset/
google oauth login
email alerts & reports - https://superset.apache.org/docs/installation/alerts-reports
map box api key
enable cors
enable templating: https://superset.apache.org/docs/installation/sql-templating
postgres db for superset 'metadata db
postgres db connector for "data db"
celery and its flower monitor - https://superset.apache.org/docs/installation/async-queries-celery
redis for flask-caching https://superset.apache.org/docs/installation/cache

Push all FEATURE flags: https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md

**Comment by fatchat** [comment]
update: 

instance set up and running on the t4d load balancer at https://dsuper.projecttech4dev.org/superset/welcome/
email alerts and reports set up, sender address is `bitwarden@projecttech4dev.org`
templating configured but not tested
superset can connect to postgres data-database on RDS 
metadata database is postgres but running in local docker not RDS
celery flower set up and running on 5555 which needs to be tunnelled to
redis for flask-caching has been set up

next:

- [ ]  google oauth
- [ ]  mapbox
- [ ]  enable cors, which `CORS_OPTIONS` are needed / what is the requirement
- [ ]  metadata db on RDS

**Comment by fatchat** [comment]
update: 

enabled google oauth
- created admin user using `fab` during setup; the `username` needs to be set to the google id of the admin user
- google login then works for this user 
- admin user creates a database connection
- admin user creates a new role granting access to this database connection
- new role also contains "can read on chart"
- admin user can create charts on this database and can create dashboards
- dashboards need to be published
- we can enable self-registration on a whitelisted domain and provide "Gamma" as the default role
- new user can self-register
- admin can assign them the additional new role on top of Gamma, this will let them see the database, chart and published report

next:
- create a new role containing the permissions of Gamma plus the two others
- specify this new role as the default for self-registrations in `config.py`

**Comment by vinod-rajasekaran** [comment]
Additional requirements:

1. evaluate best way to add upload users to system with given role
2. evaluate how can we best allow for user data filtering 

for example, with sneha, we want community organiser with identifier coid =1 to see only relevant data for them
doing this would be a lot simpler if we can pass the parameters form google oauth and use jinja templating to create user data filtering;

thinking it would work like below - open to other approaches:

1. Users and any user variables needed for filtering is added in google workspace user details by NGO
2. we pull this into superset when we create users
3. add roles to share appropriate dashboards 
4. filter data for each role by using for example coid = {{user.coid}}

https://preset.io/blog/intro-jinja-templating-apache-superset/
https://stackoverflow.com/questions/65286792/how-to-use-row-level-security-in-superset-ui

**Comment by fatchat** [comment]
adding users via python: 
- https://github.com/apache/superset/issues/3083

adding fields to the user object:
- https://github.com/apache/superset/issues/9448
- https://flask-appbuilder.readthedocs.io/en/latest/security.html#extending-the-user-model

**Comment by fatchat** [comment]
add a `blob` field to the superset user object ... can this be json?
for sneha this will be their `coid` and we will be able to use it in the jinja filters

**Comment by fatchat** [comment]
sneha is going to add custom fields to their google users

  https://support.google.com/a/answer/6208725?hl=en#zippy=%2Cadd-a-new-custom-attribute

we will retrieve these once they oauth-login and pass them on to the superset `user.blob` on user creation

**Comment by fatchat** [comment]
script to upload (insert / update) users into superset
- email
- username (google user id)
- role
- extra fields to go into user.blob

**Comment by fatchat** [comment]
We can now
- Extend Superset's User object to include a `blob` field
- Upload users from a `JSON` file
- Retrieve the `blob` field of the logged-in user from within a Jinja template
- Decode the `blob1 as `JSON` to implement a Row Level Security filter

via https://github.com/DevDataPlatform/docker-superset/pull/4

**Comment by fatchat** [comment]
`coid =('{{current_blob()}}'::json->>'coid')::integer`

**Comment by fatchat** [comment]
More documentation at 
https://docs.google.com/document/d/1DkbiWPlzMFzc83WDlLv_mALEbwvhYsPch8g2SQRxnYY/edit

**Comment by fatchat** [comment]
MoM (@siddhant3030 , Nadeem, RC)

- They would like to upgrade their existing Superset running at https://superset-sneha.openbrackets.in/
- This setup needs to be upgraded from Username+Password login to Google OAuth - this means that all existing users will need to be deleted otherwise the Google login will fail with "email address already in use"
- Once their existing user accounts are deleted, they will all log in via Google to create new accounts
- Then we will run our `uploadusers` script to set their roles, CO ids and Program codes
- We will have three Roles, each granting access to all tables. One role for COs, one for POs, PCs, APDs and PDs, and one for the CEO
- All filtering will be done via RLS. 
- We will have two RLS filters: one filtering on `coid` and `program_code`, and one only filtering on `program_code`. The first will be for the CO role, the second for the { PO, PC, APD, PD } role. There is no RLS filter for the CEO role
- SNEHA will provide an email address with credentials for use by Superset, possibly `support@snehamumbai.org`
- We will use a Tech4Dev Google application but whitelist `snehamumbai.org` in `superset_config.py`

**Comment by fatchat** [comment]
new machine has been built at sneha.dalgo.in

@siddhant3030 is exporting charts from the existing superset setup and importing them into this new one

we had trouble doing this for the dashboards, but found that doing the charts takes care of the underlying datasets

maybe once the charts are done the dashboards will follow?

**Comment by fatchat** [comment]
`DASHBOARD_EDIT_CHART_IN_NEW_TAB` is marked for deprecation

https://github.com/apache/superset/issues/23648

**Comment by fatchat** [comment]
`DRILL_TO_DETAIL` is working


![Image](https://github.com/DevDataPlatform/docker-superset/assets/2160416/25ef91c3-58b4-4f29-a1b6-24965652f7e3)

**Comment by fatchat** [comment]
`DASHBOARD_CROSS_FILTERS` is not working

**Comment by fatchat** [comment]
`HORIZONTAL_FILTER_BAR` is working



![Image](https://github.com/DevDataPlatform/docker-superset/assets/2160416/acf8938c-0a1c-4b2f-a8ec-60906a4fa0d9)

**Comment by fatchat** [comment]
`ESTIMATE_QUERY_COST`:



![Image](https://github.com/DevDataPlatform/docker-superset/assets/2160416/ab6b43b0-386b-4cb4-827b-a45b55929cb0)

**Comment by fatchat** [comment]
`SSH_TUNNELING`



![Image](https://github.com/DevDataPlatform/docker-superset/assets/2160416/b70366a8-f86b-4581-ae41-4b7c65235826)

**Comment by Abhishek-N** [comment]
`ENABLE_TEMPLATE_PROCESSING`

<img width="484" alt="Screenshot 2023-08-25 at 5 27 30 PM" src="https://github.com/DevDataPlatform/docker-superset/assets/35729337/1d5ae96d-4594-49fc-a682-e5ea99e3657b">

**Comment by Abhishek-N** [comment]
`ALERT_REPORTS`


<img width="481" alt="Screenshot 2023-08-25 at 6 15 03 PM" src="https://github.com/DevDataPlatform/docker-superset/assets/35729337/635b6bf2-c25a-4cd8-ad09-dbea688689a0">

**Comment by Abhishek-N** [comment]
`DASHBOARD_RBAC`


<img width="690" alt="Screenshot 2023-08-25 at 7 19 55 PM" src="https://github.com/DevDataPlatform/docker-superset/assets/35729337/5cc41e7e-bfbc-41cd-ad78-ae5b6a817943">

**Comment by Abhishek-N** [comment]
`ENFORCE_DB_ENCRYPTION_UI` is removed


https://github.com/apache/superset/pull/23640

**Comment by fatchat** [comment]
add vinod and siddhant into the user list

**Comment by fatchat** [comment]
DRILL BY



![Image](https://github.com/DevDataPlatform/docker-superset/assets/2160416/3cb1c3ad-b819-477e-800e-721a7cbdbfa1)

**Comment by fatchat** [comment]
Scheduled emailed reports are working now

Report
Chart CSV
Chart PNG
Chart Text

**Comment by fatchat** [comment]
@vinod-rajasekaran were you going to speak with nadeem to finalize on the roles we're going to create

**Comment by fatchat** [comment]
emails go from notifications@dalgo.in 

this has been set up to go via gmail rather than AWS because AWS is only set up to send to dalgo and pt4d addresses right now

**Comment by fatchat** [comment]
we have the blob in the user's profile now

tested: edited and verified that access changed

![Image](https://github.com/DalgoT4D/docker-superset/assets/2160416/3feb55ce-ddf1-4597-831b-b757cbb508e1)

**Comment by fatchat** [comment]
deployed user blob editing to sneha.dalgo.in

**Comment by fatchat** [comment]
the role for the majority of users should not show them the various menu items etc, copy it over from the existing superset; @vinod-rajasekaran will create a login for rohit

other roles are almost ready, we expect to have them after wednesday

training will start the week of the 25th

**Comment by fatchat** [comment]
the SNEHA role makes available the following UX

<img width="737" alt="image" src="https://github.com/DalgoT4D/docker-superset/assets/2160416/47dff874-0a67-402f-90eb-3f62bae6810d">

the top-right menu contains

<img width="227" alt="image" src="https://github.com/DalgoT4D/docker-superset/assets/2160416/d1c3ba82-8e14-4a22-b0a7-ea41b4978e79">

SQL Query is available not no databases show up:

<img width="463" alt="image" src="https://github.com/DalgoT4D/docker-superset/assets/2160416/56f761b0-4c51-468b-8c04-ed0ca7bc7721">


Create a Chart is available but no datasets show up:

<img width="376" alt="image" src="https://github.com/DalgoT4D/docker-superset/assets/2160416/3e40a400-e9d1-47ed-8006-2e87479c0a76">


And similarly Create a Dashboard is available but no charts show up. 

The role definition is:

```
on AdvancedDataType                   : can read
on Annotation                         : can read
on Annotation                         : can write
on Api                                : can query
on Api                                : can query form data
on Api                                : can time range
on AsyncEventsRestApi                 : can list
on CacheRestApi                       : can invalidate
on Chart                              : can export
on Chart                              : can read
on Chart                              : can write
on ColumnarToDatabaseView             : can this form get
on ColumnarToDatabaseView             : can this form post
on CssTemplate                        : can write
on CssTemplate                        : can read
on CsvToDatabaseView                  : can this form get
on CsvToDatabaseView                  : can this form post
on Dashboard                          : can delete embedded
on Dashboard                          : can export
on Dashboard                          : can get embedded
on Dashboard                          : can write
on Dashboard                          : can read
on DashboardFilterStateRestApi        : can read
on DashboardFilterStateRestApi        : can write
on DashboardPermalinkRestApi          : can read
on DashboardPermalinkRestApi          : can write
on Dashboards                         : menu access
on Database                           : can read
on Dataset                            : can read
on Datasource                         : can external metadata
on Datasource                         : can get
on Datasource                         : can external metadata by name
on DynamicPlugin                      : can list
on DynamicPlugin                      : can show
on EmbeddedDashboard                  : can read
on ExcelToDatabaseView                : can this form post
on ExcelToDatabaseView                : can this form get
on ExploreFormDataRestApi             : can read
on ExploreFormDataRestApi             : can write
on ExplorePermalinkRestApi            : can read
on ExplorePermalinkRestApi            : can write
on FilterSets                         : can list
on FilterSets                         : can edit
on FilterSets                         : can add
on FilterSets                         : can delete
on ImportExportRestApi                : can export
on ImportExportRestApi                : can import
on KV                                 : can store
on KV                                 : can get value
on MenuApi                            : can get
on OpenApi                            : can get
on Query                              : can read
on ReportSchedule                     : can write
on ReportSchedule                     : can read
on ResetMyPasswordView                : can this form post
on ResetMyPasswordView                : can this form get
on SavedQuery                         : can read
on SavedQuery                         : can write
on SavedQuery                         : can export
on SecurityRestApi                    : can read
on SqlLab                             : can my queries
on Superset                           : can sqllab history
on Superset                           : can filter
on Superset                           : can fetch datasource metadata
on Superset                           : can created slices
on Superset                           : can sqllab
on Superset                           : can copy dash
on Superset                           : can dashboard permalink
on Superset                           : can testconn
on Superset                           : can log
on Superset                           : can search queries
on Superset                           : can csv
on Superset                           : can tables
on Superset                           : can slice json
on Superset                           : can annotation json
on Superset                           : can warm up cache
on Superset                           : can explore json
on Superset                           : can dashboard
on Superset                           : can add slices
on Superset                           : can fave dashboards by username
on Superset                           : can profile
on Superset                           : can fave slices
on Superset                           : can favstar
on Superset                           : can share chart
on Superset                           : can fave dashboards
on Superset                           : can stop query
on Superset                           : can estimate query cost
on Superset                           : can extra table metadata
on Superset                           : can queries
on Superset                           : can schemas access for file upload
on Superset                           : can slice
on Superset                           : can user slices
on Superset                           : can datasources
on Superset                           : can share dashboard
on Superset                           : can available domains
on Superset                           : can results
on Superset                           : can sqllab table viz
on Superset                           : can recent activity
on Superset                           : can save dash
on Superset                           : can sqllab viz
on Superset                           : can import dashboards
on Superset                           : can explore
on Superset                           : can created dashboards
on Superset                           : can request access
on Superset                           : can validate sql json
on SwaggerView                        : can show
on TabStateView                       : can post
on TabStateView                       : can migrate query
on TabStateView                       : can put
on TabStateView                       : can activate
on TabStateView                       : can delete query
on TabStateView                       : can delete
on TabStateView                       : can get
on TableSchemaView                    : can expanded
on TableSchemaView                    : can delete
on TableSchemaView                    : can post
on TagView                            : can suggestions
on TagView                            : can delete
on TagView                            : can get
on TagView                            : can tagged objects
on TagView                            : can post
on UserDBModelView                    : can userinfo
on UserDBModelView                    : resetmypassword
on UserInfoEditView                   : can this form post
on UserInfoEditView                   : can this form get
```

**Comment by fatchat** [comment]
removed
- `can write` on `Chart`
- `can write` on `Dashboard`

**Comment by fatchat** [comment]
upgrade the machine to m6a.large or t4g.large

**Comment by Ishankoradia** [comment]
Can we close this once we upgrade the machine @fatchat  ?

**Comment by fatchat** [comment]
Snapshot-ted: snap-0b4d5d7c1d2ce359c

Upgraded to m6a.large

Dashboards are loading, but often require a page reload (!) . CPU was observed to briefly go up to 30% but no higher
