### ISSUE TITLE
Superset for STiR

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/docker-superset#12]

**Comment by fatchat** [comment]
https://stir.dalgo.in/

@siddhant3030 let's copy over their charts and dashboards next week

**Comment by fatchat** [comment]
@siddhant3030 could you ask STiR for an email account from which Superset emails will go

We could also send the emails from @dalgo.in ... but they may want it to go from their domain

We will start with notifications@dalgo.in

**Comment by vinod-rajasekaran** [comment]
> https://stir.dalgo.in/
> 
> @siddhant3030 let's copy over their charts and dashboards next week

I would wait on copying over charts and dashboards as they will change - probably should be done as part of the re-work on dbt and superset. We will be keeping Stir's current superset instance active until we have made the changes to the dalgo instance and switch users over.
