### ISSUE TITLE
Superset Usage dashboard

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/docker-superset#16]
Requested by STiR - I see value all across the board for all NGOs to see what usage they have ;

Unsure of how we can do this - simple web search led me to this and it implies a standard performance dashboard based on metadata : https://engineering.hometogo.com/monitor-superset-usage-via-superset-c7f9fba79525

might be better ways to accomplish this

**Comment by nairabhishek73** [comment]
https://superset.dalgo.in/superset/dashboard/10/?native_filters_key=tAhJTS8G3wVPLuhVXOzvgGPZT_7mEh2v6LfJHjg714pzVx9Yj-UiFCRPKpKGVgL-

@Ishankoradia i went through your second cut. Sharing feedback below. We can discuss over call.

Overall:
I think we need one overall page that gives a healthy snapshot.
Filters: Time, user role, Dashboard page

Visuals
1. Total users metric
2. Pie chart of count of users by role.
3. Table with bars for metric- User name, user role, metric (actions)
4. Total Dashboard pages
5. Top dashboard pages by total visits
6. Total Charts metric 
7.  Pie chart of charts by actions on the chart or views of the chart.
9. User activity over time- multi line graph by user role, metric is user actions


Users page:
- Add a time filter.
- Top users table remove the dashboards visited measure. (dashboard_id count_distinct)

Rest looks fine. Can do away if we bring it all into the overall page. We can discuss over call.

**Comment by Ishankoradia** [comment]
v. This already shown in the `Dashboards tab`. Showing it two times doesn't make sense.
vii. There are 135 charts. Doing a pie chart on it doesnt make sense. Will do top 5.

**Comment by nairabhishek73** [comment]
Hey @Ishankoradia the aim would be to have one page only. i.e. the overall page. 
This will be our V1. We should not have multiple tabs. It should be a simple overview.

**Comment by Ishankoradia** [comment]
@nairabhishek73 can you answer the other comment. 
vii. There are 135 charts. Doing a pie chart on it doesnt make sense. Will do top 5.

Rest i am done. Please review and then we can get on a call.

**Comment by Ishankoradia** [comment]
@nairabhishek73  the role filter wont be possible due to superset contraints and the way the database schema is designed in superset. Rohit and I had a long conversation on this and came to this conclusion.

**Comment by fatchat** [comment]
we need to precompute some things so we'll make a dbt project

how do we deploy this dashboard to our clients

run the dbt code on their superset metadatabase daily

what dbt code needs to be written, make a plan, make a timeline 

how do we manage this for all our superset-clients


@Ishankoradia and @fatchat to come back with a plan on oct-10 for the current metrics

**Comment by Ishankoradia** [comment]
usage metrics and deployment plan - https://docs.google.com/document/d/1n0N08g6Cmwsk7Zavx0qpDEwZgURdOMsC8fKBHcT3w7g/edit

**Comment by fatchat** [comment]
new dbt project created

**Comment by Ishankoradia** [comment]
The first version is out, check the dashboard called `Usage v1.0`. All feedbacks incorporated.

**Comment by nairabhishek73** [comment]
Planned next steps with @ashwinit4d, @vinod-rajasekaran , and @nairabhishek73 

Dashboard Deployment:
- Usage dashboard to be deployed as a separate dashboard. Analysis section to have two tabs- 1) Dashboards 2) Usage Metadata
- Deployment plan
-- Connect to each metadataset
-- Merge and union
-- Tag to org name
-- Filter on Org name
-- Role based access

Dashboard metrics:
- [Active users by role](https://superset.dalgo.in/explore/?dashboard_page_id=8CoeJIKI_F&slice_id=266) chart moved to users/dashboards tab
- Role based tab to be deleted.
- Remove fixed limits on user and dashboard activity tables- users should be able to sort by activity and see all in ascending or descending order of activity.
- @ashwinit4d will check bugs on dashboard (noted bigs on usage of filters) and list them out for @Ishankoradia

**Comment by fatchat** [comment]
Any reason we want to merge the data from all orgs into one table and then deal with restricting access by row? seems easier to just keep everyone's data separate in the first place...

**Comment by fatchat** [comment]
we will host this dashboard on our superset (either the current superset.dalgo.in or an instance dedicated to the usage dashboards). 

we will create a user for each client in that usage-superset, and store its credentials in our dalgo database. 

when a client logs into dalgo's frontend and asks for the usage dashboard, our backend will retrieve those credentials, use them to get an embedding token from superset (https://medium.com/@khushbu.adav/embedding-superset-dashboards-in-your-react-application-7f282e3dbd88) and send that token back to the frontend. 

the frontend will use that token to embed the usage dashboard

done this way, we can use RLS to restrict what this dashboard loads and presents to the user.

**Comment by fatchat** [comment]
need permission: `[can grant guest token on SecurityRestApi]`

**Comment by Ishankoradia** [comment]
- Backend will first need to hit the POST `api/v1/security/login` with the username & password to get the `jwt` token
- Using the `jwt` token above fetch a csrf token using GET `api/v1/security/csrf_token` 
- Make a request to POST `api/v1/security/guest_token` to get embedding token. For add the csrf token in the header with the key `X-CSRFToken` and use the Bearer auth with the jwt access token. Send this embed token to the frontend.

**Comment by fatchat** [comment]
https://docs.google.com/spreadsheets/d/1xY8S4BTip1Iv9PaTQrFQvqS3yVpPKL4bWxkjcbSqgKo/edit#gid=0

**Comment by fatchat** [comment]
Complete by dec-05

**Comment by Ishankoradia** [comment]
Add UI/UX to the usage dashboard to match it to our dalgo design.
