### ISSUE TITLE
Superset Email report needs tweaks

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/docker-superset#25]
1. Email report of dashboard is showing the filter in the middle of the dashboard.
2. Link to explore superset is not taking me anywhere.
3. Downloadable file is of a format that does not open on the laptop.

**Comment by fatchat** [comment]
@nairabhishek73 the monthly LAHI PMU v3 now has the filter bar at the top

BUT the fix won't work for a longer dashboard... the correct solution would be to fix the CSS
