### ISSUE TITLE
Upgrade Noora to Superset 4

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/docker-superset#41]
Noora has a Superset machine, details in VW
The `superset.env` has the remote database connection information

1. Create a new database called `noora_backup` in the same RDS using the `postgres`
2. Can re-use the same user
3. Copy from the existing database to this new one
4. Create a new `docker-superset` on the same EC2 machine
5. The `Dockerfile` must use the new version 4 base image
6. use the branch from #42  and modify as required, pick an available port etc
7. point it to the new database
8. set `APPLICATION_HOST=noora2.dalgo.in`

RC will point `noora2.dalgo.in` at the new port running on the same machine

**Comment by fatchat** [comment]
https://hub.docker.com/layers/apache/superset/4.0.1/images/sha256-dd1072bc0e0700ccbcd2a6f8f462ef17c0a3b3abf9e76d0b5ca03cf6261e4738?context=explore

**Comment by fatchat** [comment]
running on `noora2.dalgo.in`

**Comment by fatchat** [comment]
Noora has been running on Superset 4 for two weeks now

No changes were required for
- `jinja_context.py`
- `log.py`
- `baselayout.html`
- `basic.html` @himanshudube97 please verify and update this comment

**Comment by himanshudube97** [comment]
> Noora has been running on Superset 4 for two weeks now
> 
> No changes were required for
> 
> * `jinja_context.py`
> * `log.py`
> * `baselayout.html`
> * `basic.html` @himanshudube97 please verify and update this comment

Yes only the jinja_context.py was to be updated, that aslo we did, and now everything runs fine.
