### ISSUE TITLE
Update all existing Superset 3 instances with the new jinja_context

### ISSUE THREAD

**Issue by fatchat** [DalgoT4D/docker-superset#53]
- [x] sneha
- [x] stir
- [x] arghyam
- [x] inrem
- [x] atecf
- [x] shofco

**Comment by himanshudube97** [comment]
@fatchat  updated the jinja context files for all of these, except sneha. I dont have the ip or credentials to log into their superset.
-also a doubt, was the change in the jinja context file was something related to superset4 or the changes will work with superset3 too.

**Comment by fatchat** [comment]
Superset 3, I think after 3.1 maybe? So make sure all of thrm are also on the latest superset 3 that we have (3.1.3 or whatever it is)

**Comment by himanshudube97** [comment]
@fatchat  updated all with new jinja context and also with the superset image version 3.1.3

**Comment by himanshudube97** [comment]
@fatchat can you provide me the credentials for the SNEHA superset? I dont have access for them on VW

**Comment by fatchat** [comment]
@himanshudube97 thanks for letting me know, have added their IP to VW

**Comment by fatchat** [comment]
- [ ] superset3.dalgo.in
- [ ] demosuperset.dalgo.in
