### ISSUE TITLE
how to maintain the base docker image on github.

### ISSUE THREAD

**Issue by himanshudube97** [DalgoT4D/docker-superset#59]
- So right now we have a docker image that is created and pushed to dockerhub from (make-t4d). And later on dockerifle from (make-client) folder use it as a base image.

- So if we have to update the base image on dockerhub eg : apache/superset: 3.0.1 to apache/superset: 3.0.3 , so should we update the same image on dockerhub or should be add a new tag and create a new image?

 1. if we update the the same image ->
   Pros-> All supersets will fetch the updated image.
   Cons-> If the updated image has any issue or breakdown, every superset will fail and we will not have any stable image that we can point to.

  2. If, we push a new image with new tag->
  Pros-> we will have earlier images available on docker hub , along with the new image pushed.
  Cons-> Have to manually update the dockerfiles for all supsersets, to change the base_image to the latest one.
  
  Task-> Find a good way to implement this.

**Comment by himanshudube97** [comment]
@fatchat do you think is this an issue ? any thoughts?

**Comment by fatchat** [comment]
yes always make new images and update existing deployments one by one
